#!/bin/bash

input=$1
start_time=$2
duration=$3
chan_list=$4

source /home/detchar/opt/gwpysoft/etc/gwpy-user-env.sh
#echo ${input}

num=`echo $((${input}+1))|bc`

channel=`sed -n "${num}p" < ${chan_list}`

#echo $result

python find_crossings_condor.py -c ${channel} -s ${start_time} -d ${duration} -i H1
